layout_spectrum: 0.7290610419586301
typography_spectrum: 0.017192683881148696
color:
  brandColors:
    - '#E8E595'
    - '#D0A825'
    - '#40627C'
    - '#26393D'
    - '#FFFAE4'
  brandStrength: 0.9811634700745344
  lightness: 0.23650330561213195
  saturation: 0.2923119026236236
  rhythmicContrast: 0.18652641912922263
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Dale Emasiri
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: deadbadgr
description: Grid-Based Ramblings
purpose: []
