typography_spectrum: 0.62947
color:
  brandColors:
    - '#bb3f56'
    - '#43372a'
    - '#a78c64'
    - '#bccddc'
    - '#f96757'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.21733
analytics:
  google: null
  facebook: null
  twitter: null
name: Dale Emasiri
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: deadbadgr
description: Grid-Based Ramblings
purpose: []
