name: Dale Emasiri
favicon: null
layout_spectrum: 0.76039
typography_spectrum: 0.62947
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bb3f56'
    - '#43372a'
    - '#a78c64'
    - '#bccddc'
    - '#f96757'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
