layout_spectrum: 0.5367942256852984
typography_spectrum: 0.5434821671806276
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.9530721704941243
  lightness: 0.8927920230198652
  saturation: 0.2974168094806373
  rhythmicContrast: 0.5309330429881811
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Dale Emasiri
  email: demasiri@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/579ddc57-74ef-4b54-8140-4e2448668454.png
name: Dale Emasiri
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1c008cf1-60b3-4a13-af58-76d35733389b.png
title: deadbadgr
description: Grid-Based Ramblings
purpose: []
