name: Dale Emasiri
favicon: null
layout_spectrum: 0.25586
typography_spectrum: 0.47413950599730015
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#554a75'
    - '#020002'
    - '#701815'
    - '#ed8d58'
    - '#b95528'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
